    
    ///DO NOT EDIT THIS FILE AS THIS IS THE MASTER COPY, IF YOU HAVE ALREADY COPIED THE TEMPLATE FOLDER AND ARE MAKING A CUSTOM HELMET THEN PROCEED and delete this guide section when you are done <3

    // NOTE: the word TEMPLATE in these instructions will be replaced with TENPLATE to avoid the instructions being compromised while making changes 
    // so " TENPLATE " = " TEMPLATE "


    // Steps:
    // 1. Create folder with name of player for custom helmet, Copy contents of the TENPLATE folder and paste inside new custom folder.
    // 2. Override .PAAs inside folder with new custom textures making sure to swap the "TENPLATE" with the player's name e.g "Ashley"
    // 3. highlight / select > TENPLATE < inbetween the arrows and press CTRL + H, Replace "TENPLATE" with the player's name making sure to keep it case sensitive. e.g "Ashley"

    // 4. Toggle all outlining with edit> outlining> toggle all outlining. 
    // 5. Select / highlight a class name by double clicking e.g " 22nd_Ashley_HelmBase_Open " then CTRL + ALT and double click the rest of the class names, when all selected CTRL + C / Copy
    // 6. Paste the class names in the CfgPatches weapon array in the infantry/config.cpp
    // 7. with the same method as in step 5 select all of the class names individually (Double click with CTRL+ALT) and when selected press SHIFT+" to add quoatations e.g " "22nd_Ashley_HelmBase_Open" "
    // 8. Add commas to the class names after quatiations have been added, ensuring the last class of the array does not have a comma. e.g " "22nd_Ashley_HelmBase_Open", "
    
    // 9. in the same config.cpp go to the includes and paste > #include "customHelmets/TEMPLATE/TEMPLATECustomHelmet.hpp" < under the other includes in CfgWeapons !!! MAKE SURE THIS IS UNDER CFG WEAPONS !!!
    // NOTE: Step 3 should have named the avove include correclty but ensure it matches the file path and naming of this document customHelmets/Ashley/Ashleycustom.hpp ".

    // 10. Go to the infantryXtdGear.hpp located in the same folder as the config.cpp and under " class 22nd_ECH252C_Customs " follow the commented instructions.
    // 11. Test the helmet is in the game with HEMTT Launch and all version function as intended.


    class 22nd_TEMPLATE_HelmBase_Open: 22nd_Helm_base
    {
        scope = 2;
        scopeArsenal = 2;
        displayName = "[22nd] TEMPLATE's ECH252-C";
        picture = "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\iconHelmetBase.paa";
        hiddenSelections[] =
        {
            "camo1", // Helmet
            "camo2", // NVG Mount
            "camo3", // Helmet Strap
            "camo4", // Eyepiece
            "camo5", // Eyepiece Glass
            "camo6", // Glasses/Visor
            "camo7", // Vac Seal
            "Camo8", // Chin Module
            "Camo9", // Visor, Closed
            //"Helmet",
            //"NVGMount",
            //"HelmetStrap",
            "EyePiece",
            "EyePieceGlass",
            "VisorGlasses",
            "VaccumCollar",
            "Helmet_Chin",
            "Closed_Visor"
        };
        class XtdGearInfo
        {
            model = "22nd_ECH252C_Customs";
            Custom = "TEMPLATE";
            Camouflage = "WD";
            Variants = "Open";
            Decal = "None";
        };
        hiddenSelectionsTextures[] =
        {
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
        };
        class itemInfo: itemInfo
        {
             hiddenSelections[] =
             {
                "camo1", // Helmet
                "camo2", // NVG Mount
                "camo3", // Helmet Strap
                "camo4", // Eyepiece
                "camo5", // Eyepiece Glass
                "camo6", // Glasses/Visor
                "camo7", // Vac Seal
                "Camo8", // Chin Module
                "Camo9", // Visor, Closed
                //"Helmet",
                //"NVGMount",
                //"HelmetStrap",
                "EyePiece",
                "EyePieceGlass",
                "VisorGlasses",
                "VaccumCollar",
                "Helmet_Chin",
                "Closed_Visor"
            };
             hiddenSelectionsTextures[] =
            {
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
            };
        };
    };

    class 22nd_TEMPLATE_HelmBase_Closed : 22nd_Helm_base
    {
        scope = 2;
        scopeArsenal = 2;
        displayName = "[22nd] TEMPLATE's ECH252-C";
        picture = "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\iconHelmetBase.paa";
        hiddenSelections[] =
        {
            "camo1", // Helmet
            "camo2", // NVG Mount
            "camo3", // Helmet Strap
            "camo4", // Eyepiece
            "camo5", // Eyepiece Glass
            "camo6", // Glasses/Visor
            "camo7", // Vac Seal
            "Camo8", // Chin Module
            "Camo9", // Visor, Closed
            //"Helmet",
            //"NVGMount",
            //"HelmetStrap",
            "EyePiece",
            "EyePieceGlass",
            "VisorGlasses",
            "VaccumCollar",
            //"Helmet_Chin",
            //"Closed_Visor"
        };
        class XtdGearInfo
        {
            model = "22nd_ECH252C_Customs";
            Custom = "TEMPLATE";
            Camouflage = "WD";
            Variants = "Closed";
            Decal = "None";
        };
        hiddenSelectionsTextures[] =
        {
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Brown_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\22nd_Base_Helmet_Lower.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\22nd_Base_Helmet_Lower.paa",
        };
         class itemInfo: itemInfo
        {
            hiddenSelections[] =
            {
                "camo1", // Helmet
                "camo2", // NVG Mount
                "camo3", // Helmet Strap
                "camo4", // Eyepiece
                "camo5", // Eyepiece Glass
                "camo6", // Glasses/Visor
                "camo7", // Vac Seal
                "Camo8", // Chin Module
                "Camo9", // Visor, Closed
                //"Helmet",
                //"NVGMount",
                //"HelmetStrap",
                "EyePiece",
                "EyePieceGlass",
                "VisorGlasses",
                "VaccumCollar",
                //"Helmet_Chin",
                //"Closed_Visor"
            };
            hiddenSelectionsTextures[] =
            {
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Brown_CO.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\22nd_Base_Helmet_Lower.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\22nd_Base_Helmet_Lower.paa",
            };
        };
    };

    class 22nd_TEMPLATE_HelmBase_Eye : 22nd_Helm_base
    {
        scope = 2;
        scopeArsenal = 2;
        displayName = "[22nd] TEMPLATE's ECH252-C Eyepiece";
        picture = "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\iconHelmetBase.paa";
        hiddenSelections[] =
        {
            "camo1", // Helmet
            "camo2", // NVG Mount
            "camo3", // Helmet Strap
            "camo4", // Eyepiece
            "camo5", // Eyepiece Glass
            "camo6", // Glasses/Visor
            "camo7", // Vac Seal
            "Camo8", // Chin Module
            "Camo9", // Visor, Closed
            //"Helmet",
            //"NVGMount",
            //"HelmetStrap",
            //"EyePiece",
            //"EyePieceGlass",
            "VisorGlasses",
            "VaccumCollar",
            "Helmet_Chin",
            "Closed_Visor"
        };
        class XtdGearInfo
        {
            model = "22nd_ECH252C_Customs";
            Custom = "TEMPLATE";
            Camouflage = "WD";
            Variants = "Eyepiece";
            Decal = "None";
        };
        hiddenSelectionsTextures[] =
        {
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
        };
        class itemInfo: itemInfo
        {
            hiddenSelections[] =
            {
                "camo1", // Helmet
                "camo2", // NVG Mount
                "camo3", // Helmet Strap
                "camo4", // Eyepiece
                "camo5", // Eyepiece Glass
                "camo6", // Glasses/Visor
                "camo7", // Vac Seal
                "Camo8", // Chin Module
                "Camo9", // Visor, Closed
                //"Helmet",
                //"NVGMount",
                //"HelmetStrap",
                //"EyePiece",
                //"EyePieceGlass",
                "VisorGlasses",
                "VaccumCollar",
                "Helmet_Chin",
                "Closed_Visor"
            };
            hiddenSelectionsTextures[] =
            {
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
            };
        };
    };

    class 22nd_TEMPLATE_HelmBase_Visor : 22nd_Helm_base
    {
        scope = 2;
        scopeArsenal = 2;
        author = "Warhound Mod Team";
        displayName = "[22nd] TEMPLATE's ECH252-C Visor";
        model = "MA_Armor\data\Helmets\CH252\CH252_Helm.p3d";
        picture = "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\iconHelmetBase.paa";
        hiddenSelections[] =
        {
            "camo1", // Helmet
            "camo2", // NVG Mount
            "camo3", // Helmet Strap
            "camo4", // Eyepiece
            "camo5", // Eyepiece Glass
            "camo6", // Glasses/Visor
            "camo7", // Vac Seal
            "Camo8", // Chin Module
            "Camo9", // Visor, Closed
            //"Helmet",
            //"NVGMount",
            //"HelmetStrap",
            "EyePiece",
            "EyePieceGlass",
            //"VisorGlasses",
            "VaccumCollar",
            "Helmet_Chin",
            "Closed_Visor"
        };
        class XtdGearInfo
        {
            model = "22nd_ECH252C_Customs";
            Custom = "TEMPLATE";
            Camouflage = "WD";
            Variants = "Visor";
            Decal = "None";
        };
        hiddenSelectionsTextures[] =
        {
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
        };
        class itemInfo: itemInfo
        {
            hiddenSelections[] =
            {
                "camo1", // Helmet
                "camo2", // NVG Mount
                "camo3", // Helmet Strap
                "camo4", // Eyepiece
                "camo5", // Eyepiece Glass
                "camo6", // Glasses/Visor
                "camo7", // Vac Seal
                "Camo8", // Chin Module
                "Camo9", // Visor, Closed
                //"Helmet",
                //"NVGMount",
                //"HelmetStrap",
                "EyePiece",
                "EyePieceGlass",
                //"VisorGlasses",
                "VaccumCollar",
                "Helmet_Chin",
                "Closed_Visor"
            };
            hiddenSelectionsTextures[] =
            {
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Base_TEMPLATEHelmet_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
            };
        };
    };


    //Infantry Medic
    class 22nd_TEMPLATE_HelmBase_Open_med : 22nd_Helm_base
    {
        scope = 2;
        scopeArsenal = 2;
        displayName = "[22nd] TEMPLATE's ECH252-MED";
        picture = "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\iconHelmetBaseMed.paa";
        hiddenSelections[] =
        {
            "camo1", // Helmet
            "camo2", // NVG Mount
            "camo3", // Helmet Strap
            "camo4", // Eyepiece
            "camo5", // Eyepiece Glass
            "camo6", // Glasses/Visor
            "camo7", // Vac Seal
            "Camo8", // Chin Module
            "Camo9", // Visor, Closed
            //"Helmet",
            //"NVGMount",
            //"HelmetStrap",
            "EyePiece",
            "EyePieceGlass",
            "VisorGlasses",
            "VaccumCollar",
            "Helmet_Chin",
            "Closed_Visor"
        };
        hiddenSelectionsTextures[] =
        {
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa", 
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa"
        };
        class XtdGearInfo
        {
            model = "22nd_ECH252C_Customs";
            Custom = "TEMPLATE";
            Camouflage = "WD";
            Variants = "Open";
            Decal = "Medical";
        };
        class itemInfo: itemInfo
        {
            hiddenSelections[] =
            {
                "camo1", // Helmet
                "camo2", // NVG Mount
                "camo3", // Helmet Strap
                "camo4", // Eyepiece
                "camo5", // Eyepiece Glass
                "camo6", // Glasses/Visor
                "camo7", // Vac Seal
                "Camo8", // Chin Module
                "Camo9", // Visor, Closed
                //"Helmet",
                //"NVGMount",
                //"HelmetStrap",
                "EyePiece",
                "EyePieceGlass",
                "VisorGlasses",
                "VaccumCollar",
                "Helmet_Chin",
                "Closed_Visor"
            };
            hiddenSelectionsTextures[] =
            {
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa", 
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa"
            };
        };
    };

    class 22nd_TEMPLATE_HelmBase_Closed_med : 22nd_Helm_base
    {
        scope = 2;
        scopeArsenal = 2;
        displayName = "[22nd] TEMPLATE's ECH252-MED Closed";
        picture = "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\iconHelmetBaseMed.paa";
        hiddenSelections[] =
        {
            "camo1", // Helmet
            "camo2", // NVG Mount
            "camo3", // Helmet Strap
            "camo4", // Eyepiece
            "camo5", // Eyepiece Glass
            "camo6", // Glasses/Visor
            "camo7", // Vac Seal
            "Camo8", // Chin Module
            "Camo9", // Visor, Closed
            //"Helmet",
            //"NVGMount",
            //"HelmetStrap",
            "EyePiece",
            "EyePieceGlass",
            "VisorGlasses",
            "VaccumCollar",
            //"Helmet_Chin",
            //"Closed_Visor"
        };
        class XtdGearInfo
        {
            model = "22nd_ECH252C_Customs";
            Custom = "TEMPLATE";
            Camouflage = "WD";
            Variants = "Closed";
            Decal = "Medical";
        };
        hiddenSelectionsTextures[] =
        {
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Brown_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\22nd_Base_Helmet_Lower.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\22nd_Base_Helmet_Lower.paa"
        };
        class itemInfo: itemInfo
        {
            hiddenSelections[] =
            {
                "camo1", // Helmet
                "camo2", // NVG Mount
                "camo3", // Helmet Strap
                "camo4", // Eyepiece
                "camo5", // Eyepiece Glass
                "camo6", // Glasses/Visor
                "camo7", // Vac Seal
                "Camo8", // Chin Module
                "Camo9", // Visor, Closed
                //"Helmet",
                //"NVGMount",
                //"HelmetStrap",
                "EyePiece",
                "EyePieceGlass",
                "VisorGlasses",
                "VaccumCollar",
                //"Helmet_Chin",
                //"Closed_Visor"
            };
            hiddenSelectionsTextures[] =
            {
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Brown_CO.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\22nd_Base_Helmet_Lower.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\22nd_Base_Helmet_Lower.paa"
            };
        };
    };

    class 22nd_TEMPLATE_HelmBase_Eye_med : 22nd_Helm_base
    {
        scope = 2;
        scopeArsenal = 2;
        displayName = "[22nd] TEMPLATE's ECH252-MED Eyepiece ";
        picture = "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\iconHelmetBaseMed.paa";
        hiddenSelections[] =
        {
            "camo1", // Helmet
            "camo2", // NVG Mount
            "camo3", // Helmet Strap
            "camo4", // Eyepiece
            "camo5", // Eyepiece Glass
            "camo6", // Glasses/Visor
            "camo7", // Vac Seal
            "Camo8", // Chin Module
            "Camo9", // Visor, Closed
            //"Helmet",
            //"NVGMount",
            //"HelmetStrap",
            //"EyePiece",
            //"EyePieceGlass",
            "VisorGlasses",
            "VaccumCollar",
            "Helmet_Chin",
            "Closed_Visor"
        };
        class XtdGearInfo
        {
            model = "22nd_ECH252C_Customs";
            Custom = "TEMPLATE";
            Camouflage = "WD";
            Variants = "Eyepiece";
            Decal = "Medical";
        };
        hiddenSelectionsTextures[] =
        {
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa"
        };
         class itemInfo: itemInfo
        {
            hiddenSelections[] =
            {
                "camo1", // Helmet
                "camo2", // NVG Mount
                "camo3", // Helmet Strap
                "camo4", // Eyepiece
                "camo5", // Eyepiece Glass
                "camo6", // Glasses/Visor
                "camo7", // Vac Seal
                "Camo8", // Chin Module
                "Camo9", // Visor, Closed
                //"Helmet",
                //"NVGMount",
                //"HelmetStrap",
                //"EyePiece",
                //"EyePieceGlass",
                "VisorGlasses",
                "VaccumCollar",
                "Helmet_Chin",
                "Closed_Visor"
            };
            hiddenSelectionsTextures[] =
            {
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa"
            };
        };
    };

    class 22nd_TEMPLATE_HelmBase_Visor_med : 22nd_Helm_base
    {
        scope = 2;
        scopeArsenal = 2;
        displayName = "[22nd] TEMPLATE's ECH252-MED Visor";
        picture = "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\iconHelmetBaseMed.paa";
        hiddenSelections[] =
        {
            "camo1", // Helmet
            "camo2", // NVG Mount
            "camo3", // Helmet Strap
            "camo4", // Eyepiece
            "camo5", // Eyepiece Glass
            "camo6", // Glasses/Visor
            "camo7", // Vac Seal
            "Camo8", // Chin Module
            "Camo9", // Visor, Closed
            //"Helmet",
            //"NVGMount",
            //"HelmetStrap",
            "EyePiece",
            "EyePieceGlass",
            //"VisorGlasses",
            "VaccumCollar",
            "Helmet_Chin",
            "Closed_Visor"
        };
        class XtdGearInfo
        {
            model = "22nd_ECH252C_Customs";
            Custom = "TEMPLATE";
            Camouflage = "WD";
            Variants = "Visor";
            Decal = "Medical";
        };
        hiddenSelectionsTextures[] =
        {
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
        };
        class itemInfo: itemInfo
        {
            hiddenSelections[] =
            {
                "camo1", // Helmet
                "camo2", // NVG Mount
                "camo3", // Helmet Strap
                "camo4", // Eyepiece
                "camo5", // Eyepiece Glass
                "camo6", // Glasses/Visor
                "camo7", // Vac Seal
                "Camo8", // Chin Module
                "Camo9", // Visor, Closed
                //"Helmet",
                //"NVGMount",
                //"HelmetStrap",
                "EyePiece",
                "EyePieceGlass",
                //"VisorGlasses",
                "VaccumCollar",
                "Helmet_Chin",
                "Closed_Visor"
            };
             hiddenSelectionsTextures[] =
            {
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\BaseMed_TEMPLATEHelmet_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
            };
        };
    };


    //Infantry Winter

    class 22nd_TEMPLATE_HelmSnow_Open : 22nd_Helm_base
    {
        scope = 2;
        scopeArsenal = 2; 
        displayName = "[22nd] TEMPLATE's ECH252-C/W";
        picture = "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\iconHelmetWinter.paa";
        hiddenSelections[] =
        {
            "camo1", // Helmet
            "camo2", // NVG Mount
            "camo3", // Helmet Strap
            "camo4", // Eyepiece
            "camo5", // Eyepiece Glass
            "camo6", // Glasses/Visor
            "camo7", // Vac Seal
            "Camo8", // Chin Module
            "Camo9", // Visor, Closed
            //"Helmet",
            //"NVGMount",
            //"HelmetStrap",
            "EyePiece",
            "EyePieceGlass",
            "VisorGlasses",
            "VaccumCollar",
            "Helmet_Chin",
            "Closed_Visor"
        };
        hiddenSelectionsTextures[] =
        {
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa"
        };
        class XtdGearInfo
        {
            model = "22nd_ECH252C_Customs";
            Custom = "TEMPLATE";
            Camouflage = "Winter";
            Variants = "Open";
            Decal = "None";
        };
        class ItemInfo : ItemInfo
        {
            hiddenSelections[] =
            {
                "camo1", // Helmet
                "camo2", // NVG Mount
                "camo3", // Helmet Strap
                "camo4", // Eye Piece
                "camo5", // Eye Piece Glass
                "camo6", // Visor Glasses
                "camo7", // Vac Seal
                "Camo8", // Face Module Chin
                "Camo9", // Closed Visor
                //"Helmet",
                //"NVGMount",
                //"HelmetStrap",
                "EyePiece",
                "EyePieceGlass",
                "VisorGlasses",
                "VaccumCollar",
                "Helmet_Chin",
                "Closed_Visor"
            };
              hiddenSelectionsTextures[] =
              {
                  "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa",
                  "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa",
                  "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa",
                  "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                  "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                  "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
                  "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
                  "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
                  "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
              };
              
        };
    }; 

    class 22nd_TEMPLATE_HelmSnow_Closed : 22nd_Helm_base
    {
        scope = 2;
        scopeArsenal = 2;
        displayName = "[22nd] TEMPLATE's ECH252-C/W Closed";
        picture = "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\iconHelmetWinter.paa";
        hiddenSelections[] =
        {
            "camo1", // Helmet
            "camo2", // NVG Mount
            "camo3", // Helmet Strap
            "camo4", // Eyepiece
            "camo5", // Eyepiece Glass
            "camo6", // Glasses/Visor
            "camo7", // Vac Seal
            "Camo8", // Chin Module
            "Camo9", // Visor, Closed
            //"Helmet",
            //"NVGMount",
            //"HelmetStrap",
            "EyePiece",
            "EyePieceGlass",
            "VisorGlasses",
            "VaccumCollar",
            //"Helmet_Chin",
            //"Closed_Visor"
        };
        class XtdGearInfo
        {
            model = "22nd_ECH252C_Customs";
            Custom = "TEMPLATE";
            Camouflage = "Winter";
            Variants = "Closed";
            Decal = "None";
        };
        hiddenSelectionsTextures[] =
        {
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Brown_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
        };
        class ItemInfo : ItemInfo
        {
            uniformModel = "MA_Armor\data\Helmets\CH252\CH252_Helm.p3d";
            hiddenSelections[] =
            {
                "camo1", // Helmet
                "camo2", // NVG Mount
                "camo3", // Helmet Strap
                "camo4", // Eye Piece
                "camo5", // Eye Piece Glass
                "camo6", // Visor Glasses
                "camo7", // Vac Seal
                "Camo8", // Face Module Chin
                "Camo9", // Closed Visor
                //"Helmet",
                //"NVGMount",
                //"HelmetStrap",
                "EyePiece",
                "EyePieceGlass",
                "VisorGlasses",
                "VaccumCollar",
                //"Helmet_Chin",
                //"Closed_Visor"
            };
            hiddenSelectionsTextures[] =
            {
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Eyepiece
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Eyepiece Glass
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Visor Glass
                "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa", // Vac Collar
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa", // Face Module Chin
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa" // Closed Visor
            };
        };
    };
    class 22nd_TEMPLATE_HelmSnow_Eye : 22nd_Helm_base
    {
        scope = 2;
        scopeArsenal = 2;
        displayName = "[22nd] TEMPLATE's ECH252-C/W Eyepiece";
        picture = "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\iconHelmetWinter.paa";
        hiddenSelections[] =
        {
            "camo1", // Helmet
            "camo2", // NVG Mount
            "camo3", // Helmet Strap
            "camo4", // Eyepiece
            "camo5", // Eyepiece Glass
            "camo6", // Glasses/Visor
            "camo7", // Vac Seal
            "Camo8", // Chin Module
            "Camo9", // Visor, Closed
            //"Helmet",
            //"NVGMount",
            //"HelmetStrap",
            //"EyePiece",
            //"EyePieceGlass",
            "VisorGlasses",
            "VaccumCollar",
            "Helmet_Chin",
            "Closed_Visor"
        };
        hiddenSelectionsTextures[] =
        {
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa", // Helmet Texture
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa", // Helmet Texture
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa", // Helmet Texture
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
        };
        class XtdGearInfo
        {
            model = "22nd_ECH252C_Customs";
            Custom = "TEMPLATE";
            Camouflage = "Winter";
            Variants = "Eyepiece";
            Decal = "None";
        };
        class ItemInfo : ItemInfo
        {
            uniformModel = "MA_Armor\data\Helmets\CH252\CH252_Helm.p3d";
            hiddenSelections[] =
            {
                "camo1", // Helmet
                "camo2", // NVG Mount
                "camo3", // Helmet Strap
                "camo4", // Eye Piece
                "camo5", // Eye Piece Glass
                "camo6", // Visor Glasses
                "camo7", // Vac Seal
                "Camo8", // Face Module Chin
                "Camo9", // Closed Visor
                //"Helmet",
                //"NVGMount",
                //"HelmetStrap",
                //"EyePiece",
                //"EyePieceGlass",
                "VisorGlasses",
                "VaccumCollar",
                "Helmet_Chin",
                "Closed_Visor"
            };
            hiddenSelectionsTextures[] =
            {
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Eyepiece
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Eyepiece Glass
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Visor Glass
                "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa", // Vac Collar
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa", // Face Module Chin
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa" // Closed Visor
            };
        };
    };
    class 22nd_TEMPLATE_HelmSnow_Visor : 22nd_Helm_base
    {
        scope = 2;
        scopeArsenal = 2;
        displayName = "[22nd] TEMPLATE's ECH252-C/W Visor";
        picture = "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\iconHelmetWinter.paa";
        hiddenSelections[] =
        {
            "camo1", // Helmet
            "camo2", // NVG Mount
            "camo3", // Helmet Strap
            "camo4", // Eye Piece
            "camo5", // Eye Piece Glass
            "camo6", // Visor Glasses
            "camo7", // Vac Seal
            "Camo8", // Face Module Chin
            "Camo9", // Closed Visor
            //"Helmet",
            //"NVGMount",
            //"HelmetStrap",
            "EyePiece",
            "EyePieceGlass",
            //"VisorGlasses",
            "VaccumCollar",
            "Helmet_Chin",
            "Closed_Visor"
        };
        hiddenSelectionsTextures[] =
        {
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa", // Helmet Texture
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa", // Helmet Texture
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa", // Helmet Texture
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Eyepiece
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Eyepiece Glass
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Visor Glass
            "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa", // Vac Collar
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa", // Face Module Chin
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa" // Closed Visor
        };
        class XtdGearInfo
        {
            model = "22nd_ECH252C_Customs";
            Custom = "TEMPLATE";
            Camouflage = "Winter";
            Variants = "Visor";
            Decal = "None";
        };
        class ItemInfo : ItemInfo
        {
            uniformModel = "MA_Armor\data\Helmets\CH252\CH252_Helm.p3d";
            hiddenSelections[] =
            {
                "camo1", // Helmet
                "camo2", // NVG Mount
                "camo3", // Helmet Strap
                "camo4", // Eye Piece
                "camo5", // Eye Piece Glass
                "camo6", // Visor Glasses
                "camo7", // Vac Seal
                "Camo8", // Face Module Chin
                "Camo9", // Closed Visor
                //"Helmet",
                //"NVGMount",
                //"HelmetStrap",
                "EyePiece",
                "EyePieceGlass",
                //"VisorGlasses",
                "VaccumCollar",
                "Helmet_Chin",
                "Closed_Visor"
            };
            hiddenSelectionsTextures[] =
            {
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\Winter_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Eyepiece
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Eyepiece Glass
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Visor Glass
                "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa", // Vac Collar
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa", // Face Module Chin
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa" // Closed Visor
            };
        };
    };


    //Infantry Medic Winter
    class 22nd_TEMPLATE_HelmSnow_Open_med : 22nd_Helm_base
    {
        scope = 2;
        scopeArsenal = 2;
        displayName = "[22nd] TEMPLATE's ECH252-MED/W MED";
        picture = "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\iconHelmetWinterMed.paa";
        hiddenSelections[] =
        {
            "camo1", // Helmet
            "camo2", // NVG Mount
            "camo3", // Helmet Strap
            "camo4", // Eyepiece
            "camo5", // Eyepiece Glass
            "camo6", // Glasses/Visor
            "camo7", // Vac Seal
            "Camo8", // Chin Module
            "Camo9", // Visor, Closed
            //"Helmet",
            //"NVGMount",
            //"HelmetStrap",
            "EyePiece",
            "EyePieceGlass",
            "VisorGlasses",
            "VaccumCollar",
            "Helmet_Chin",
            "Closed_Visor"
        };
        hiddenSelectionsTextures[] =
        {
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa"
        };
        class XtdGearInfo
        {
            model = "22nd_ECH252C_Customs";
            Custom = "TEMPLATE";
            Camouflage = "Winter";
            Variants = "Open";
            Decal = "Medical";
        };
        class ItemInfo : ItemInfo
        {
            hiddenSelections[] =
            {
                "camo1", // Helmet
                "camo2", // NVG Mount
                "camo3", // Helmet Strap
                "camo4", // Eye Piece
                "camo5", // Eye Piece Glass
                "camo6", // Visor Glasses
                "camo7", // Vac Seal
                "Camo8", // Face Module Chin
                "Camo9", // Closed Visor
                //"Helmet",
                //"NVGMount",
                //"HelmetStrap",
                "EyePiece",
                "EyePieceGlass",
                "VisorGlasses",
                "VaccumCollar",
                "Helmet_Chin",
                "Closed_Visor"
            };
            hiddenSelectionsTextures[] =
            {
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Eyepiece
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Eyepiece Glass
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Visor Glass
                "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa", // Vac Collar
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa", // Face Module Chin
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa" // Closed Visor
            };
        };
    };

    class 22nd_TEMPLATE_HelmSnow_Closed_med : 22nd_Helm_base
    {
        scope = 2;
        scopeArsenal = 2;
        displayName = "[22nd] TEMPLATE's ECH252-MED/W MED Closed";
        picture = "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\iconHelmetWinterMed.paa";
        hiddenSelections[] =
        {
            "camo1", // Helmet
            "camo2", // NVG Mount
            "camo3", // Helmet Strap
            "camo4", // Eyepiece
            "camo5", // Eyepiece Glass
            "camo6", // Glasses/Visor
            "camo7", // Vac Seal
            "Camo8", // Chin Module
            "Camo9", // Visor, Closed
            //"Helmet",
            //"NVGMount",
            //"HelmetStrap",
            "EyePiece",
            "EyePieceGlass",
            "VisorGlasses",
            "VaccumCollar",
            //"Helmet_Chin",
            //"Closed_Visor"
        };
        class XtdGearInfo
        {
            model = "22nd_ECH252C_Customs";
            Custom = "TEMPLATE";
            Camouflage = "Winter";
            Variants = "Closed";
            Decal = "Medical";
        };
        hiddenSelectionsTextures[] =
        {
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Brown_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
        };
        class ItemInfo : ItemInfo
        {
            hiddenSelections[] =
            {
                "camo1", // Helmet
                "camo2", // NVG Mount
                "camo3", // Helmet Strap
                "camo4", // Eye Piece
                "camo5", // Eye Piece Glass
                "camo6", // Visor Glasses
                "camo7", // Vac Seal
                "Camo8", // Face Module Chin
                "Camo9", // Closed Visor
                //"Helmet",
                //"NVGMount",
                //"HelmetStrap",
                "EyePiece",
                "EyePieceGlass",
                "VisorGlasses",
                "VaccumCollar",
                //"Helmet_Chin",
                //"Closed_Visor"
            };
            hiddenSelectionsTextures[] =
            {
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Eyepiece
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Eyepiece Glass
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Visor Glass
                "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa", // Vac Collar
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa", // Face Module Chin
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa" // Closed Visor
            };
        };
    };

    class 22nd_TEMPLATE_HelmSnow_Eye_med : 22nd_Helm_base
    {
        scope = 2;
        scopeArsenal = 2;
        displayName = "[22nd] TEMPLATE's ECH252-MED/W Eyepiece";
        picture = "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\iconHelmetWinterMed.paa";
        hiddenSelections[] =
        {
            "camo1", // Helmet
            "camo2", // NVG Mount
            "camo3", // Helmet Strap
            "camo4", // Eyepiece
            "camo5", // Eyepiece Glass
            "camo6", // Glasses/Visor
            "camo7", // Vac Seal
            "Camo8", // Chin Module
            "Camo9", // Visor, Closed
            //"Helmet",
            //"NVGMount",
            //"HelmetStrap",
            //"EyePiece",
            //"EyePieceGlass",
            "VisorGlasses",
            "VaccumCollar",
            "Helmet_Chin",
            "Closed_Visor"
        };
        hiddenSelectionsTextures[] =
        {
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
        };
        class XtdGearInfo
        {
            model = "22nd_ECH252C_Customs";
            Custom = "TEMPLATE";
            Camouflage = "Winter";
            Variants = "Eyepiece";
            Decal = "Medical";
        };
        class ItemInfo : ItemInfo
        {
            hiddenSelections[] =
            {
                "camo1", // Helmet
                "camo2", // NVG Mount
                "camo3", // Helmet Strap
                "camo4", // Eye Piece
                "camo5", // Eye Piece Glass
                "camo6", // Visor Glasses
                "camo7", // Vac Seal
                "Camo8", // Face Module Chin
                "Camo9", // Closed Visor
                //"Helmet",
                //"NVGMount",
                //"HelmetStrap",
                //"EyePiece",
                //"EyePieceGlass",
                "VisorGlasses",
                "VaccumCollar",
                "Helmet_Chin",
                "Closed_Visor"
            };
            hiddenSelectionsTextures[] =
            {
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Eyepiece
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Eyepiece Glass
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Visor Glass
                "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa", // Vac Collar
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa", // Face Module Chin
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa" // Closed Visor
            };
        };
    };

    class 22nd_TEMPLATE_HelmSnow_Visor_med : 22nd_Helm_base
    {
        scope = 2;
        scopeArsenal = 2;
        displayName = "[22nd] TEMPLATE's ECH252-MED/W Visor";
        picture = "\z\22ndRDF\addons\uniforms\helmets\Infantry\data\base\iconHelmetWinterMed.paa";
        hiddenSelections[] =
        {
            "camo1", // Helmet
            "camo2", // NVG Mount
            "camo3", // Helmet Strap
            "camo4", // Eyepiece
            "camo5", // Eyepiece Glass
            "camo6", // Glasses/Visor
            "camo7", // Vac Seal
            "Camo8", // Chin Module
            "Camo9", // Visor, Closed
            //"Helmet",
            //"NVGMount",
            //"HelmetStrap",
            "EyePiece",
            "EyePieceGlass",
            //"VisorGlasses",
            "VaccumCollar",
            "Helmet_Chin",
            "Closed_Visor"
        };
        class XtdGearInfo
        {
            model = "22nd_ECH252C_Customs";
            Custom = "TEMPLATE";
            Camouflage = "Winter";
            Variants = "Visor";
            Decal = "Medical";
        };
        hiddenSelectionsTextures[] =
        {
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa",
            "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
            "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa",
        };
        class ItemInfo : ItemInfo
        {
            hiddenSelections[] =
            {
                "camo1", // Helmet
                "camo2", // NVG Mount
                "camo3", // Helmet Strap
                "camo4", // Eye Piece
                "camo5", // Eye Piece Glass
                "camo6", // Visor Glasses
                "camo7", // Vac Seal
                "Camo8", // Face Module Chin
                "Camo9", // Closed Visor
                //"Helmet",
                //"NVGMount",
                //"HelmetStrap",
                "EyePiece",
                "EyePieceGlass",
                //"VisorGlasses",
                "VaccumCollar",
                "Helmet_Chin",
                "Closed_Visor"
            };
            hiddenSelectionsTextures[] =
            {
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "\z\22ndRDF\addons\uniforms\helmets\Infantry\customHelmets\template\WinterMed_TEMPLATEHelmet_CO.paa", // Helmet Texture
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Eyepiece
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Eyepiece Glass
                "MA_Armor\data\Helmets\CH252\data\MA_HelmetAccessories_A_CO.paa", // Visor Glass
                "MA_Armor\data\Helmets\CH252\data\VaccumCollar\Base\VacSeal_Base_CO.paa", // Vac Collar
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa", // Face Module Chin
                "MA_Armor\data\Helmets\CH252\data\SealedVisor\Blue_Visor\Base\FaceModule_CO.paa" // Closed Visor
            };
        };
    };
