units[]=
{
	"22nd_Bulldog_MG",
	"22nd_Javelin_2_A_Bulldog_MG",
	"22nd_Pike_1_1_Bulldog_MG",
	"22nd_Pike_1_2_Bulldog_MG",
	"22nd_Pike_1_3_Bulldog_MG",
	"22nd_Pike_1_A_Bulldog_MG",
	// "22nd_UNSC_Reach_AntiTank",
	// "22nd_UNSC_Reach_AutoRifleman",
	// "22nd_UNSC_Reach_Crewman",
	// "22nd_UNSC_Reach_Demo",
	// "22nd_UNSC_Reach_Grenadier",
	// "22nd_UNSC_Reach_Marksman",
	// "22nd_UNSC_Reach_Medic",
	// "22nd_UNSC_Reach_RTO",
	// "22nd_UNSC_Reach_Rifleman",
	// "22nd_UNSC_Reach_Sniper",
	"Warhound_Bayonet_Orca_Default",
	"Warhound_Bayonet_Orca_Stealth",
	"Warhound_Bayonet_Orca_3",
	"Warhound_Bayonet_Stealth_Orca_3",
	"Warhound_Bayonet_Orca_4",
	"Warhound_Pelican_ARMY",
	"Warhound_Pelican_Orca_1",
	"Warhound_Pelican_Orca_2",
	"Warhound_Pelican_Orca_3",
	"Warhound_Pelican_Orca_4",
	"22nd_M808BM_Scorpion",
	"22nd_M808BM_Lancer_Scorpion",
	"22ndRDFM808BFND_Scorpion", // Fix for Jr Dev
	"Warhound_Oryx",
	"22nd_Oryx_Pike1A",
	"22nd_Oryx_Pike11",
	"22nd_Oryx_Pike12",
	"22nd_Oryx_Pike13",
	"22nd_144_Falcon_Armed",
	"22nd_144_Falcon_Unarmed",
	"22nd_144S_Falcon_Armed",
	"22nd_144S_Falcon_Unarmed",
	"22nd_144AGL_Falcon",
	"22nd_Hornet",
	"22nd_Hornet_CAP",
	"22nd_Hornet_CAS",
};
